# <span style="color:darkblue"> Lecture 8: Local/Global and Apply </span>

<font size = "5">

In the previous lecture we ...

- Worked through the definition of functions
- Illustrated some examples

In this lecture, we will ...

- Discuss the syntax of functions (local/global)
- Apply functions to multiple elements in a data frame
- Introduce ".py" files

In [101]:
# "global" command - use to permanently modify a variable. 
# create an empty dataframe; add variables to the data frame
# use "apply(myfunction)" to apply functions to modify data frame
# create / drop a variable
# use "map()" function to execute a specified function for each item in a list/an array.
# import scripts.example_functions as ef
# from scripts.example_variables import *

## <span style="color:darkblue"> I. Import Libraries </span>

In [102]:
# the "pandas" library is for manipualting datasets

import pandas as pd
import numpy as np

## <span style="color:darkblue"> II. Local/Global Variables </span>

<font size="5"> 

Most of the variables we've defined so far are "global"

- Stored in working environment
- Can be referenced in other parts of the notebook

<font size = "5">
Example:

In [103]:
message_hello = "hello"
number3       = 3
#check "jupter variables" to see what variables you have created so far

In [104]:
print(message_hello + " world")
print(number3 * 2)

hello world
6

<font size = "5">

Any "global" variable can be referenced inside functions

- However, this can lead to mistakes
- Preferrably, include **all** the inputs as parameters

<font size = "5">

$f(x,y,z) = x + y + z$

In [105]:
# Correct Example:
def fn_add_recommended(x,y,z):      # define the function name and the parameters of the function
    return(x + y + z)               # define the function "fn_add_recommended(x,y,z) = x+y+z"

print(fn_add_recommended(x = 1, y = 2, z = 5))       # add the argument (the value) for each parameter (x,y,z)
print(fn_add_recommended(x = 1, y = 2, z = 10))

8
13

In [106]:
# Example that runs (but not recommended)
# Python will try to fill in any missing inputs       
# with variables in the working environment
def fn_add_notrecommended(x,y):         # referencing a global variable in a function. There is a "mis-match" between the information and the input set you are provided.
    return(x + y + z)                   # the message from return is what will print out? How does return works. WHy print (fn_add_notrecommended) gives (x+y+z)?
                                        # when the function is defined with 3 parameters but only 2 of them are provided the a local variable value, the other parameter, in this case
                                        # the Z value will be got from the global variable. 
z = 5           
print(fn_add_notrecommended(x = 1, y = 2))      
z = 10
print(fn_add_notrecommended(x = 1, y = 2))

8
13

<font size ="5">

Variables defined inside functions are "local"

- Stored "temporarily" while running
- Includes: Parameters + Intermediate variables

<font size = "5">

Local variables supercede global variables

In [107]:
# This is an example where we define a quadratic function
# (x,y) are both local variables of the function
# 
# When we call the function, only the arguments matter.
# any intermediate value inside the function

def fn_square(x):
    y = x**2
    return(y)

print(fn_square(x = 1))

# What if we define the X and Y as global variables that does not match the defined function. Which value will it be used to perform the function?
x = 10
y = -5

print(x)
print(y)
print(fn_square(x))

# We can tell it used the X global parameter variable. 
# Local variables supercede/take-over 取代 global variables. 
# The Y value resulted from the performed function does not replace the Y value defined in the global. Y is still -5 if check in Jupyter variable.

1
10
-5
100

<font size = "5">

Local variables are **not** stored in the working environment

In [108]:
# The following code assigns a global variable x
# Inside the function

x = 5
y = 4

def fn_square(x):
    y = x**2
    return(y)

print("Example 1:")
print(fn_square(x = 10))
print(x)
print(y)

print("Example 2:")
print(fn_square(x = 20))
print(x)
print(y)

Example 1:
100
5
4
Example 2:
400
5
4

<font size = "5">

To permanently modify a variable, use the "global" command

In [109]:
def modify_x():    
    global x
    x = x + 5

# modify_x is a function that permanently increasing x by 5 everytime the function is used. 

x = 1
# Now, running the function wil permanently increase x by 5. 
modify_x()
print(x)

6

In [110]:
modify_x()
print(x)

11

<font size = "5">

Try it yourself:

- What happens if we run "modify_x" twice?
- What happens if we add "global y" inside "fn_square"?

In [111]:
# Write your own code here

def modify_x():
    global x
    x = x * 5

x = 1

# modify x for the 1st time
modify_x()
print (x)       # Now the X value is 5. 

# modify x for the 2nd time
modify_x()
print (x)

5
25

In [112]:
# Now the X value is 25. 

def fn_square_changed(x):           # defined a function with x parameter
    global y                        # defined a global variable "y"
    y = x**2                        # defined the global variable y = x**2                      
    return 2                        # return a value/message is number 2
 
y = 1
print(fn_square_changed(x=10))
print(y)

y = 0
print(fn_square_changed(x=5))       # no matter what x value is. The return value is said to be 2. Only 2 is going to be printed out.
                                    # However, everytime we change the x value/enter a new x value, the y value will be new defined as the global y variable = x**2
print(y)
# Remember the local vairable takes over the global variable. Adding a global variable to the defined function with a local variable does not change the answer.

2
100
2
25

## <span style="color:darkblue"> III. Operations over data frames (apply/map) </span>

<font size = "5">

Create an empty data frame

In [113]:
data  = pd.DataFrame()

In [114]:
print(data)

Empty DataFrame
Columns: []
Index: []

<font size = "5">

Add variables

In [115]:
# The following are lists with values for different individuals
# "age" is the number of years
# "num_underage_siblings" is the total number of underage siblings
# "num_adult_siblings" is the total number of adult siblings

data["age"] = [18,29,15,32,6]
data["num_underage_siblings"] = [0,0,1,1,0]
data["num_adult_siblings"] = [1,0,0,1,0]

#Q: I am confused why 32 is counted as both underage and adult??? And the "6" year old is not put in any categoty???
#A: The age in the row is not corresponding to the # num_underage or # num_adult in the same row. It does not matter where is "1" is put in the row.

In [116]:
data

   age  num_underage_siblings  num_adult_siblings
0   18                      0                   1
1   29                      0                   0
2   15                      1                   0
3   32                      1                   1
4    6                      0                   0

<font size = "5">

Define functions

In [117]:
# The first two functions return True/False depending on age constraints
# The third function returns the sum of two numbers
# These are defined function. To use them, use the "apply" function shown later in the doc. 

fn_iseligible_vote = lambda age: age >= 18

fn_istwenties = lambda age: (age >= 20) & (age < 30)

fn_sum = lambda x,y: x + y

In [118]:
# The fourt function returns a string with the age bracket

def fn_agebracket(age):
    if (age >= 18):
        status = "Adult"
    elif (age >= 10) & (age < 18):
        status = "Adolescent"
    else:
        status = "Child"
    return(status)

<font size = "5">
Applying functions with one argument: <br>

```python
 apply(myfunction)
 ```
 - Takes a dataframe series (a column vector) as an input
 - Computes function separately for each individual

In [119]:
# The fucntion "apply" will extract each element and return the function value
# It is similar to running a "for-loop" over each element

data["can_vote"]    = data["age"].apply(fn_iseligible_vote)
data["in_twenties"] = data["age"].apply(fn_istwenties)
data["age_bracket"] = data["age"].apply(fn_agebracket)


# NOTE: The following code also works:
# data["can_vote"]    = data["age"].apply(lambda age: age >= 18)
# data["in_twenties"] = data["age"].apply(lambda age: (age >= 20) & (age < 30))

display(data)

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket
0,18,0,1,True,False,Adult
1,29,0,0,True,True,Adult
2,15,1,0,False,False,Adolescent
3,32,1,1,True,False,Adult
4,6,0,0,False,False,Child

<font size = "5">

Creating a new variable

In [120]:
data['new_var'] = data['age'].apply(lambda age: age >= 18)  #Q: Why do we use '' instead of "" for the 'age' in this case??? A: Both are fine. 
data

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket,new_var
0,18,0,1,True,False,Adult,True
1,29,0,0,True,True,Adult,True
2,15,1,0,False,False,Adolescent,False
3,32,1,1,True,False,Adult,True
4,6,0,0,False,False,Child,False

<font size = "5">

Dropping an existing variable

In [121]:
data = data.drop(columns=['new_var'])
data

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket
0,18,0,1,True,False,Adult
1,29,0,0,True,True,Adult
2,15,1,0,False,False,Adolescent
3,32,1,1,True,False,Adult
4,6,0,0,False,False,Child

<font size = "5">

Mapping functions with one or more arguments <br>

**Definition:** The ```map()``` function executes a <br>
specified function for each item in an iterable <br>
(such as a list or an array). <br>
 The item is sent to the function as a parameter.

```python
list(map(myfunction, list1,list2, ....))
```

In [122]:
list(map(fn_iseligible_vote, data["age"]))

[True, True, False, True, False]

In [123]:
# Repeat the above example with map
# We use list() to convert the output to a list
# The first argument of map() is a function
# The following arguments are the subarguments of the function

data["can_vote_map"] = list(map(fn_iseligible_vote, data["age"]))

In [124]:
# In this example, there are more than two arguments

data["num_siblings"] = list(map(fn_sum,
                                data["num_underage_siblings"],
                                data["num_adult_siblings"]))

In [125]:
list(map(fn_sum, 
         data["num_underage_siblings"], 
         data["num_adult_siblings"]))

# for variables in two lists, they add by sequence in the list.

[1, 0, 1, 2, 0]

In [126]:
data["num_underage_siblings"] + data["num_adult_siblings"]

# in the following run result, the left column is the sequence (0-4), the right column is the corresponding summed data.

0    1
1    0
2    1
3    2
4    0
dtype: int64

In [127]:
data["num_underage_siblings"]

0    0
1    0
2    1
3    1
4    0
Name: num_underage_siblings, dtype: int64

In [128]:
data["num_adult_siblings"]

0    1
1    0
2    0
3    1
4    0
Name: num_adult_siblings, dtype: int64

In [129]:
data["num_siblings"]

0    1
1    0
2    1
3    2
4    0
Name: num_siblings, dtype: int64

<font size = "5">

<span style="color:darkgreen"> Recommended! </span>

- Arguments can be split into multiple lines!
- Start a separate line after a comma
- Experts recommend each line has 80 characters or less

In [130]:
data["num_siblings"] = list(map(fn_sum,
                                data["num_underage_siblings"],
                                data["num_adult_siblings"]))

<font size = "5">

Try it yourself!

- Write a function checking whether num_siblings $\ge$ 1
- Add a variable to the dataset called "has_siblings"
- Assign True/False to this variable using "apply()"

In [131]:
# Write your own code

data["has_siblings"]  = data["num_siblings"].apply(lambda num: num>= 1)
data

# I did not assign "True/False" to the variable. Does the "apply()" function build in with true or false result?

,age,num_underage_siblings,num_adult_siblings,can_vote,in_twenties,age_bracket,can_vote_map,num_siblings,has_siblings
0,18,0,1,True,False,Adult,True,1,True
1,29,0,0,True,True,Adult,True,0,False
2,15,1,0,False,False,Adolescent,False,1,True
3,32,1,1,True,False,Adult,True,2,True
4,6,0,0,False,False,Child,False,0,False

<font size = "5">

Try it yourself!

- Read the car dataset "data_raw/features.csv"
- Create a function that tests whether mpg $\ge$ 29
- Add a variable "mpg_above_29" which is True/False if mpg $\ge$ 29
- Store the new dataset to "data_clean/features.csv"

In [132]:
# Write your own code

carfeatures = pd.read_csv("data_raw/features.csv")

carfeatures['mpg_above_29'] = carfeatures['mpg'].apply(lambda mpg: mpg >= 29)
print(carfeatures)

carfeatures.to_csv("data_clean/features.csv", index=False)

# the index is essentially the row labels used to identify each row (from 0,1,2 - default)
# Setting index = False omits the index column so it won’t appear in the CSV.

      mpg  cylinders  displacement horsepower  weight  acceleration  \
0    18.0          8           307        130    3504          12.0
1    15.0          8           350        165    3693          11.5
2    18.0          8           318        150    3436          11.0
3    16.0          8           304        150    3433          12.0
4    17.0          8           302        140    3449          10.5
..    ...        ...           ...        ...     ...           ...
393  27.0          4           140         86    2790          15.6
394  44.0          4            97         52    2130          24.6
395  32.0          4           135         84    2295          11.6
396  28.0          4           120         79    2625          18.6
397  31.0          4           119         82    2720          19.4

    vehicle_id  mpg_above_29
0    C-1689780         False
1    B-1689791         False
2    P-1689802         False
3    A-1689813         False
4    F-1689824         False
..         ...           ...
393  F-1694103         False
394  V-1694114          True
395  D-1694125          True
396  F-1694136         False
397  C-1694147          True

[398 rows x 8 columns]

<font size = "5">

Try it yourself!

- Map can also be applied to simple lists!
- Create a lambda function with arguments {fruit,color}.
- The function returns the string <br>
" A {fruit} is {color}"
- Create the following two lists:

``` list_fruits  = ["banana","strawberry","kiwi"] ```

``` list_colors  = ["yellow","red","green"] ```
- Use the list(map()) function to output a list with the form

In [133]:
# Write your own code

fn_sum = lambda fruit, color: "A "+ fruit +" is "+ color +"" 

list_fruits = ["banana","strawberry","kiwi"]
list_colors  = ["yellow","red","green"]

list(map(fn_sum,list_fruits,list_colors))

['A banana is yellow', 'A strawberry is red', 'A kiwi is green']

## <span style="color:darkblue"> IV. (Optional) External Scripts </span>

<font size = "5">

".ipynb" files ...

- Markdown + python code
- Great for interactive output!

".py" files ...

- Python (only) script
- Used for specific tasks
- Why? Split code into smaller, more manageable files


<font size = "5">

<table><tr>
<td style = "border:0px"> <img src="figures/screenshot_py_functions.png" alt="drawing" width="300"/>  </td>
<td style = "border:0px">

File with functions

 </td>
</tr></table>

**A module is just a Python program that ends with <br>
.py extension and a folder that contains a <br>
 module becomes a package!**

<font size = "5">

We can import functions into the working <br>
environment from a file

In [134]:
import scripts.example_functions as ef

<font size = "5">

We reference them using the alias

In [135]:
x = 1
print(ef.fn_quadratic(1))
print(ef.fn_quadratic(5))

ef.message_hello("Juan")

1
25

'hi Juan'


<font size = "5">

<table><tr>
<td style = "border:0px"> <img src="figures/screenshot_py_variables.png" alt="drawing" width="300"/>  </td>
<td style = "border:0px">

File with variables

- Storing values/settings
- Variables are global <br>
(can be referenced later)

</td>
</tr></table>

<font size = "5">

We can also import and reference variables

In [136]:
import scripts.example_variables as ev

In [137]:
# When we run this program
# # the value of alpha will be overwritten

alpha = 1
print(alpha)
print(ev.alpha)

1
5

<font size = "5">

We can also use ``` from ``` and ``` * ``` <br>
to import variables directly into the working <br>
environment

In [138]:
from scripts.example_variables import *

print(alpha)
print(beta)
print(gamma)
print(delta)

5
10
20
100